services:
  backend:
    environment:
      - API=751331aff809428f9a4100329250304
    ports:
      - "8080:8080"
    networks:
      - web
    build:
        context: backend
        dockerfile: Dockerfile

  frontend:
    image: frontend
    ports :
        - "80:9000"
    networks:
      - web
    build:
        context: frontend
        dockerfile: Dockerfile
    depends_on:
        [backend]

networks:
  web:
